### PR TITLE
Fix Water_State_Bubbler's rand behavior

### LINKED ISSUE #277: Water_State_Bubbler has incorrect behavior.
In the steam version of Mania (as well as Sonic 3), there's a very small chance where Water_State_Bubbler can create a VERY small bugged bubble instead of a big one:

image

this does not happen on the decomp.

### PR DESCRIPTION
**Pull request by Jdsle**
Fixes #277 
image

### CODE REVIEW

File: SonicMania/Objects/Common/Water.c [hunk 1]
```diff
@@ -1131,10 +1131,10 @@ void Water_State_Bubbler(void)
     }
 
     if (self->visible && RSDK.CheckOnScreen(self, &self->updateRange)) {
-        if (!self->countdownID) {
+        if (--self->countdownID <= 0) {
```
Comment (Mefiresu) [inline SonicMania/Objects/Common/Water.c:1134]: From Steam:
image
```suggestion
        if (--self->countdownID < 0) {
```
